services:
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:443"
  mariadb:
    container_name: mariadb
    build:
      context: mariadb
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - /Users/raphaelperrot/SynologyDrive/Documents/inception/data/mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build:
      context: wordpress
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env