services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - backend
      - frontend
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    healthcheck:
          test: [ "CMD", "nc", "-z", "wordpress", "9000" ]
          interval: 1s
          retries: 40

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: always
    networks:
      - frontend
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    secrets:
      - ssl_key
      - ssl_crt
    volumes:
      - wordpress_data:/var/www/html

secrets:
  ssl_key:
    file: "../.SECRETS/private_key.key"
  ssl_crt:
    file: "../.SECRETS/certificate.crt"

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/rperrot/data/mariadb'
      o: 'bind'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/rperrot/data/wordpress'
      o: 'bind'

networks:
  frontend:
    name: frontend
  backend:
    name: backend